animsin += sinn
alarm[0]=6
/*animsin += sinn
headx = (x-1.6 + cos((animsin / 3)))
heady = (y-30 + sin((animsin / 1.5)))
bodyx = (x-1.6 + cos((animsin / 3)))
bodyy = (y+13 + (sin((animsin / 1.5)) / 1.5))
legx = x
legy = y+60
alarm[0]=5